name: build-ios-ipa
on:
  push:
    branches:
    - ci-build-ios-artifacts
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup build identity
      env:
        BUILD_CERT_BASE64: ${{ secrets.BUILD_ID_CERT_BASE64 }}
        BUILD_CERT_PASS: ${{ secrets.BUILD_ID_CERT_PASS }}
        BUILD_PROVISIONING: ${{ secrets.BUILD_ID_PROVISIONING }}
        KEYCHAIN_PASS: ${{ secrets.BUILD_ID_KEYCHAIN_PASS }}
      run: |
        # create variables
        BUILD_CERT_PATH=$RUNNER_TEMP/build_certificate.p12
        BUILD_PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERT_BASE64" | base64 --decode --output $BUILD_CERT_PATH
        echo -n "$BUILD_PROVISIONING" | base64 --decode --output $BUILD_PP_PATH
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASS" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASS" $KEYCHAIN_PATH
        # import certificate to keychain
        security import $BUILD_CERT_PATH -P "$BUILD_CERT_PASS" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $BUILD_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.10'
        channel: 'stable'
        architecture: x64

    - run: pushd example; flutter pub get

    - run: pushd example; flutter build ipa --export-options-plist=./ios/exportOptions.plist

    - name: Archive IPA
      uses: actions/upload-artifact@v3
      with:
        name: ipa-app-release
        path: example/build/ios/ipa/argyle_link_flutter_example.ipa

    - name: Upload app to browserstack
      run: |
        curl \
         -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }} \
         -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
         -F "file=@example/build/ios/ipa/argyle_link_flutter_example.ipa" \
         -F 'data={"custom_id": "ios_flutter_latest"}'
