name: build-ios-ipa
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Import Codesigning Certificate
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_CERT_P12 }}
        p12-password: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_CERT_PASS }}

    - name: Install Provisioning Profile
      uses: akiojin/install-provisioning-profile-github-action@v1.0
      with:
        base64: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_PROVISIONING }}

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - run: pushd example; flutter pub get

    - run: pushd example; flutter build ipa --dart-define=IS_INTERNAL_JSON_BUILD=true --export-options-plist=./ios/exportOptions.plist

    - name: Archive IPA
      uses: actions/upload-artifact@v4
      with:
        name: ipa-app-release
        path: example/build/ios/ipa/argyle_link_flutter_example.ipa
