name: build-ios-ipa
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: argyle-systems/argyle-link-github-actions/setup-ios-build-identity@main
      with:
        cert-base64: ${{ secrets.BUILD_ID_CERT_BASE64 }}
        cert-pass: ${{ secrets.BUILD_ID_CERT_PASS }}
        provisioning-base64: ${{ secrets.BUILD_ID_PROVISIONING }}
        keychain-pass: ${{ secrets.BUILD_ID_KEYCHAIN_PASS }}

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.10'
        channel: 'stable'
        architecture: x64

    - run: pushd example; flutter pub get

    - run: pushd example; flutter build ipa --dart-define=IS_INTERNAL_JSON_BUILD=true --export-options-plist=./ios/exportOptions.plist

    - name: Archive IPA
      uses: actions/upload-artifact@v3
      with:
        name: ipa-app-release
        path: example/build/ios/ipa/argyle_link_flutter_example.ipa

    - name: Upload app to browserstack
      run: |
        curl \
         -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }} \
         -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
         -F "file=@example/build/ios/ipa/argyle_link_flutter_example.ipa" \
         -F 'data={"custom_id": "ios_flutter_latest"}'
