name: publish-sdk
on:
  push:
    tags:
      - '*.*.*'
jobs:
  publish-sdk:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - id: Extract git tag
        run: echo "DEPLOY_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set SDK version
        run: |
          sed -i "s/version: \"0.0.1\" # %LINK_VERSION%/version: \"${{ steps.tag.outputs.DEPLOY_TAG }}\"/g" pubspec.yaml

      - name: Publish
        run: flutter pub publish --force
