name: publish-sdk
on:
  push:
    tags:
      - '*.*.*'
jobs:
  publish-sdk:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - id: tag
        run: echo "DEPLOY_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set SDK version
        run: |
          sed -i "s/version: \"0.0.1\" # %LINK_VERSION%/version: \"${{ steps.tag.outputs.DEPLOY_TAG }}\"/g" pubspec.yaml

      - name: Publish
        run: flutter pub publish --force
