name: publish-sdk
on:
  push:
    tags:
      - '*.*.*'
jobs:
  publish-sdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
