name: Secret Scanning

on: [ pull_request ]

jobs:
  run:
    uses: argyle-systems/argyle-security-workflows/.github/workflows/secret-scanning-shared.yaml@613bb323597342084d96351ee03a34f74cdc5a6e # v1.1.17
    secrets: inherit
